"""init

Revision ID: 2d547b718332
Revises: 3cd17252875c
Create Date: 2020-03-21 13:33:34.638415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d547b718332'
down_revision = '3cd17252875c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
